#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2021 Oracle.  All Rights Reserved.
#
# FS QA Test No. 1209
#
# Try invalid parameters to see if they fail.

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -r -f $tmp.* $dir
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/reflink

# real QA test starts here
_require_xfs_io_command swapext '-v vfs'
_require_xfs_io_command startupdate
_require_test
_require_scratch
_require_chattr i

rm -f $seqres.full

dir=$TEST_DIR/test-$seq
mkdir -p $dir
blksz=65536
nrblks=64

_scratch_mkfs >> $seqres.full
_scratch_mount

_pwrite_byte 0x58 0 $((blksz * nrblks)) $dir/a >> $seqres.full
_pwrite_byte 0x58 0 $((blksz * nrblks)) $dir/b >> $seqres.full

echo Immutable files
$XFS_IO_PROG -c 'chattr +i' -c "swapext $dir/b" $dir/a
$CHATTR_PROG -i $dir/a

echo Readonly files
$XFS_IO_PROG -r -c "swapext $dir/b" $dir/a

echo Directories
$XFS_IO_PROG -c "swapext $dir/b" $dir

echo Unaligned ranges
$XFS_IO_PROG -c "swapext -s 37 -d 61 -l 17 $dir/b" $dir/a

echo file1 range entirely beyond EOF
$XFS_IO_PROG -c "swapext -s $(( blksz * (nrblks + 500) )) -d 0 -l $blksz $dir/b" $dir/a

echo file2 range entirely beyond EOF
$XFS_IO_PROG -c "swapext -d $(( blksz * (nrblks + 500) )) -s 0 -l $blksz $dir/b" $dir/a

echo Both ranges entirely beyond EOF
$XFS_IO_PROG -c "swapext -d $(( blksz * (nrblks + 500) )) -s $(( blksz * (nrblks + 500) )) -l $blksz $dir/b" $dir/a

echo file1 range crossing EOF
$XFS_IO_PROG -c "swapext -s $(( blksz * (nrblks - 1) )) -d 0 -l $((2 * blksz)) $dir/b" $dir/a

echo file2 range crossing EOF
$XFS_IO_PROG -c "swapext -d $(( blksz * (nrblks  - 1) )) -s 0 -l $((2 * blksz)) $dir/b" $dir/a

echo Both ranges crossing EOF
$XFS_IO_PROG -c "swapext -d $(( blksz * (nrblks - 1) )) -s $(( blksz * (nrblks - 1) )) -l $((blksz * 2)) $dir/b" $dir/a

echo file1 unaligned EOF to file2 nowhere near EOF
_pwrite_byte 0x58 $((blksz * nrblks)) 37 $dir/a >> $seqres.full
_pwrite_byte 0x59 $((blksz * nrblks)) 37 $dir/b >> $seqres.full
$XFS_IO_PROG -c "swapext -d 0 -s $(( blksz * nrblks )) -l 37 $dir/b" $dir/a

echo file2 unaligned EOF to file1 nowhere near EOF
$XFS_IO_PROG -c "swapext -s 0 -d $(( blksz * nrblks )) -l 37 $dir/b" $dir/a

echo Files of unequal length
_pwrite_byte 0x58 $((blksz * nrblks)) $((blksz * 2)) $dir/a >> $seqres.full
_pwrite_byte 0x59 $((blksz * nrblks)) $blksz $dir/b >> $seqres.full
$XFS_IO_PROG -c "swapext $dir/b" $dir/a

echo Files on different filesystems
_pwrite_byte 0x58 0 $((blksz * nrblks)) $SCRATCH_MNT/c >> $seqres.full
$XFS_IO_PROG -c "swapext $SCRATCH_MNT/c" $dir/a

echo Files on different mounts
mkdir -p $SCRATCH_MNT/xyz
mount --bind $dir $SCRATCH_MNT/xyz --bind
_pwrite_byte 0x60 0 $((blksz * (nrblks + 2))) $dir/c >> $seqres.full
$XFS_IO_PROG -c "swapext $SCRATCH_MNT/xyz/c" $dir/a
umount $SCRATCH_MNT/xyz

echo Swapping a file with itself
$XFS_IO_PROG -c "swapext $dir/a" $dir/a

# success, all done
status=0
exit
