#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2006 Silicon Graphics, Inc.  All Rights Reserved.
#
# FSQA Test No. 131
#
# lock test created from CXFSQA test lockfile_simple
#
. ./common/test_names
_set_seq_and_groups perms auto quick


# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/locktest

trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
_supported_fs generic
_require_test
_require_test_fcntl_advisory_locks

_run_locktest

exit
