#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2009 Eric Sandeen.  All Rights Reserved.
#
# FS QA Test No. 207
#
# Run aio-dio-extend-stat - test race in dio aio completion
#
. ./common/test_names
_set_seq_and_groups auto aio quick

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here

_supported_fs generic
_require_test

_run_aiodio aio-dio-extend-stat

exit $status
