#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2009 Eric Sandeen.  All Rights Reserved.
#
# FS QA Test No. 208
#
# Run aio-dio-invalidate-failure - test race in read cache invalidation
#
. ./common/test_names
_set_seq_and_groups auto aio

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here

_supported_fs generic
_require_test

rm -f $seqres.full

_run_aiodio aio-dio-invalidate-failure

_check_dmesg _filter_aiodio_dmesg

exit $status
