#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2009 Eric Sandeen.  All Rights Reserved.
#
# FS QA Test No. 211
#
# Run aio-free-ring-with-bogus-nr-pages - test aio_setup_ring with bad nr_pages
#
. ./common/test_names
_set_seq_and_groups auto aio quick

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here

_supported_fs generic
_require_test

_run_aiodio aio-free-ring-with-bogus-nr-pages

exit $status
