#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
#    Copyright (c) 2010 Intel Corporation
#
# FS QA Test No. 248
#
# Test for pwrite hang problem when writing from mmaped buffer of the same page 
#
. ./common/test_names
_set_seq_and_groups auto quick rw

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -f $tmp.* $TESTFILE
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here

# Modify as appropriate.
_supported_fs generic
_require_test

TESTFILE=$TEST_DIR/test_file
TEST_PROG=$here/src/pwrite_mmap_blocked

$TEST_PROG $TESTFILE

# success, all done
status=0
exit
