#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2014 Hannes Frederic Sowa.  All Rights Reserved.
#
# FS QA Test No. 339
#
# Test that directory hash entries are place in the correct order.
# commit f5ea110 ("xfs: add CRCs to dir2/da node blocks") left the
# directory with incorrect hash ordering.
#
. ./common/test_names
_set_seq_and_groups auto dir

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here
_supported_fs generic
_require_scratch
_require_test_program "dirhash_collide"

rm -f $seqres.full
_scratch_mkfs >>$seqres.full 2>&1
_scratch_mount

echo "Silence is golden"

testdir=$SCRATCH_MNT/$seq.$$
mkdir -p $testdir
$here/src/dirhash_collide -d -n 10000 $testdir >>$seqres.full 2>&1

# check the scratch device
_scratch_unmount
_check_scratch_fs

# remove all test dirs and let test harness check scratch fs again
_scratch_mount
rm -rf $testdir

# success, all done
status=0
exit
