#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Christoph Hellwig.  All Rights Reserved.
#
# FS QA Test 463
#
# Test racy COW AIO write completions.
#
. ./common/test_names
_set_seq_and_groups auto quick clone

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
	rm -f $TEST_DIR/file $TEST_DIR/clone
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/reflink

# remove previous $seqres.full before test
rm -f $seqres.full

_supported_fs generic

_require_test
_require_test_reflink
_require_aiodio aio-dio-cow-race

$AIO_TEST $TEST_DIR/file $TEST_DIR/clone

echo "Silence is golden"
status=0
exit
