#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2019, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No. 591
#
# Test using splice() to read from pipes.

. ./common/test_names
_set_seq_and_groups auto quick rw pipe splice

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $TEST_DIR/a
}

# get standard environment, filters and checks
. ./common/rc

# real QA test starts here
_supported_fs generic
_require_test
_require_odirect
_require_test_program "splice-test"

rm -f $seqres.full

$here/src/splice-test -r $TEST_DIR/a
$here/src/splice-test -rd $TEST_DIR/a
$here/src/splice-test $TEST_DIR/a
$here/src/splice-test -d $TEST_DIR/a

# success, all done
status=0
exit
