#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2021 Christian Brauner.  All Rights Reserved.
#
# FS QA Test 633
#
# Test that idmapped mounts behave correctly.
#
. ./common/test_names
_set_seq_and_groups auto quick atime attr cap idmapped io_uring mount perms rw unlink

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

_supported_fs generic
_require_idmapped_mounts
_require_test

echo "Silence is golden"

$here/src/idmapped-mounts/idmapped-mounts --device "$TEST_DEV" --mount "$TEST_DIR" --fstype "$FSTYP"

status=$?
exit
