#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 023
#
# Ensure that the populate helpers actually /can/ populate a ext4
# filesystem with all types of metadata and create an image of the
# metadata.  Check that fsck is happy with the resulting fs.
#
. ./common/test_names
_set_seq_and_groups auto quick scrub

trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_fs ext4
_require_scratch

echo "Format and populate"
_scratch_populate_cached > $seqres.full 2>&1

echo "Mount"
_scratch_mount >> $seqres.full 2>&1

# success, all done
status=0
exit
