#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2014 Red Hat, Inc.  All Rights Reserved.
#
# FS QA Test No. xfs/007
#
# Test to verify Q_XQUOTARM functionality.
#
. ./common/test_names
_set_seq_and_groups auto quota quick

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/quota

# Modify as appropriate.
_supported_fs xfs

_require_scratch
_require_xfs_quota

rm -f $seqres.full

_scratch_mkfs_xfs | _filter_mkfs > /dev/null 2> $tmp.mkfs
. $tmp.mkfs

get_qfile_nblocks() {
	local selector="$(_scratch_xfs_find_metafile "$1")"
	_scratch_xfs_db -c "$selector" -c "p core.nblocks"
}

do_test()
{
	qino_1=$1
	qino_2=$2
	off_opts=$3

	echo "*** umount"
	_scratch_unmount

	echo "*** Usage before quotarm ***"
	get_qfile_nblocks $qino_1
	get_qfile_nblocks $qino_2

	_qmount
	echo "*** turn off $off_opts quotas"
	xfs_quota -x -c "off -$off_opts" $SCRATCH_MNT
	xfs_quota -x -c "remove -$off_opts" $SCRATCH_MNT
	echo "*** umount"
	_scratch_unmount

	echo "*** Usage after quotarm ***"
	get_qfile_nblocks $qino_1
	get_qfile_nblocks $qino_2
}


# Test user and group first
_qmount_option "uquota,gquota"
_qmount
do_test uquotino gquotino ug

# Test user and project. Note that pquotino only exists on v5 (crc=1)
# superblocks. Older supers reuse gquotino.
PQUOTINO=pquotino
if [ $_fs_has_crcs == 0 ]; then
	PQUOTINO=gquotino
fi
_qmount_option "uquota,pquota"
_qmount
_require_prjquota $SCRATCH_DEV
do_test uquotino $PQUOTINO up

# success, all done
status=0
exit
