#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2001 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 038
#
# Test xfsdump/restore to a remote linux tape 
#
. ./common/test_names
_set_seq_and_groups dump ioctl remote tape

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	_cleanup_dump
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/dump

# real QA test starts here
_supported_fs xfs

_require_tape $RMT_TAPE_DEV
_create_dumpdir_fill
_erase_hard
_do_dump
_do_restore
_diff_compare

# success, all done
status=0
exit
