#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2001 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 046
#
# check on symlinks permissions
#
. ./common/test_names
_set_seq_and_groups dump ioctl auto quick

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	_cleanup_dump
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/dump

# real QA test starts here
_supported_fs xfs

_create_dumpdir_symlinks
_do_dump_file
_do_restore_file
_ls_compare_sub

# success, all done
status=0
exit
