#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2001 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 048
#
# test return codes from xfsctl on bad userspace address
#
. ./common/test_names
_set_seq_and_groups other auto quick

trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

_cleanup()
{
    cd /
    rm -f $tmp.*
}

# real QA test starts here
_supported_fs xfs
_require_test

$here/src/fault $TEST_DIR || exit

# success, all done
status=0
exit
