#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2002 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 063
#
# xfsdump/xfsrestore with EAs
#
. ./common/test_names
_set_seq_and_groups dump attr auto quick

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	_cleanup_dump
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/dump
. ./common/attr

# real QA test starts here
_supported_fs xfs

_require_attrs trusted user

# create files with EAs
_create_dumpdir_fill_ea

_do_dump_file
_do_restore_file

# need to compare EAs
# so need to get them back
_diff_compare_eas

# success, all done
status=0
exit
