#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2021 Oracle.  All Rights Reserved.
#
# FS QA Test No. 1202
#
# Simple tests of the old xfs swapext ioctl

. ./common/test_names
_set_seq_and_groups auto quick swapext

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -r -f $tmp.* $dir
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here
_supported_fs xfs
_require_xfs_io_command swapext '-v vfs'
_require_test

rm -f $seqres.full

dir=$TEST_DIR/test-$seq
mkdir -p $dir

$XFS_IO_PROG -f -c 'pwrite -S 0x58 0 256k -b 1m' $dir/a >> $seqres.full
$XFS_IO_PROG -f -c 'pwrite -S 0x59 0 256k -b 1m' $dir/b >> $seqres.full
$XFS_IO_PROG -f -c 'pwrite -S 0x60 0 256k -b 1m' $dir/c >> $seqres.full
$XFS_IO_PROG -f -c 'pwrite -S 0x61 0 128k -b 1m' $dir/d >> $seqres.full
md5sum $dir/a $dir/b $dir/c $dir/d | _filter_test_dir

# Swap two files that are the same length
echo swap
$XFS_IO_PROG -c "swapext $dir/b" $dir/a
md5sum $dir/a $dir/b | _filter_test_dir

# Try to swap two files that are not the same length
echo fail swap
$XFS_IO_PROG -c "swapext $dir/c" $dir/d
md5sum $dir/c $dir/d | _filter_test_dir

# success, all done
status=0
exit
