#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2021 Oracle.  All Rights Reserved.
#
# FS QA Test No. 1500
#
# Populate a XFS filesystem and fuzz every superblock field.
# Try online repair and, if necessary, offline repair,
# to test the most likely usage pattern.

. ./common/test_names
_set_seq_and_groups dangerous_fuzzers dangerous_bothrepair

trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_fs xfs
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Fuzz superblock"
_scratch_xfs_fuzz_metadata '' 'both' 'sb 1' >> $seqres.full
echo "Done fuzzing superblock"

# success, all done
status=0
exit
