#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2020 Oracle, Inc.  All rights reserved.
#
# FS QA Test No. 1536
#
# Populate a XFS filesystem and fuzz every project dquot field.
# Try online repair and, if necessary, offline repair,
# to test the most likely usage pattern.

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy
. ./common/quota

# real QA test starts here
_supported_fs xfs
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check
_require_quota

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1
echo "${MOUNT_OPTIONS}" | grep -q 'prjquota' || _notrun "project quota disabled"

echo "Fuzz project 0 dquot"
_scratch_xfs_fuzz_metadata '' 'both'  "dquot -p 0" >> $seqres.full
echo "Done fuzzing dquot"

# success, all done
status=0
exit
