#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2021 Oracle.  All Rights Reserved.
#
# FS QA Test No. 1539
#
# Populate a XFS filesystem and fuzz every rtrefcountbt record field.
# Use xfs_repair to fix the corruption.

. ./common/test_names
_set_seq_and_groups dangerous_fuzzers dangerous_scrub dangerous_repair realtime

trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy
. ./common/reflink

# real QA test starts here
_supported_fs xfs
_require_realtime
_require_scratch_reflink
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

inode_ver=$(_scratch_xfs_get_metadata_field "core.version" 'path -m /realtime/0.refcount')

echo "Fuzz rtrefcountbt recs"
_scratch_xfs_fuzz_metadata '' 'offline' 'path -m /realtime/0.refcount' "addr u${inode_ver}.rtrefcbt.ptrs[1]" >> $seqres.full
echo "Done fuzzing rtrefcountbt recs"

# success, all done
status=0
exit
