#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2022 Oracle.  All Rights Reserved.
#
# FS QA Test No. 1543
#
# Populate a XFS filesystem and fuzz every rtrefcountbt key/ptr field.
# Use xfs_repair to fix the corruption.

. ./common/preamble
_begin_fstest dangerous_fuzzers dangerous_scrub dangerous_repair realtime

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy
. ./common/reflink

# real QA test starts here
_supported_fs xfs
_require_realtime
_require_scratch_reflink
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

inode_ver=$(_scratch_xfs_get_metadata_field "core.version" 'path -m /realtime/0.refcount')

echo "Fuzz rtrefcountbt keyptrs"
_scratch_xfs_fuzz_metadata '(rtrefcbt)' 'offline' 'path -m /realtime/0.refcount' >> $seqres.full
echo "Done fuzzing rtrefcountbt keyptrs"

# success, all done
status=0
exit
