#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2021 Oracle.  All Rights Reserved.
#
# FS QA Test No. 1554
#
# Populate a XFS filesystem and fuzz the data mappings of every directory type.
# Use xfs_scrub to fix the corruption.
#
. ./common/preamble
_begin_fstest dangerous_fuzzers dangerous_scrub dangerous_online_repair

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_fs xfs
_require_scratch_xfs_fuzz_fields

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

# Now fuzz the block maps of each directory type.
for dirtype in BLOCK LEAF LEAFN NODE; do
	echo "Fuzz block map for ${dirtype}"
	_scratch_mount
	inum=$(stat -c '%i' $SCRATCH_MNT/S_IFDIR.FMT_${dirtype})
	_scratch_unmount

	_scratch_xfs_fuzz_metadata 'u*.bmx' 'online'  "inode ${inum}" >> $seqres.full
	echo "Done fuzzing dir map ${dirtype}"
done

# success, all done
status=0
exit
