#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2021 Oracle.  All Rights Reserved.
#
# FS QA Test No. 1557
#
# Populate a XFS filesystem and fuzz the attr mappings of every xattr type.
# Use xfs_repair to fix the corruption.
#
. ./common/preamble
_begin_fstest dangerous_fuzzers dangerous_scrub dangerous_repair

_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_fs xfs
_require_scratch_xfs_fuzz_fields

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

# Now fuzz the block maps of each attr type.
for attrtype in EXTENTS_REMOTE3K EXTENTS_REMOTE4K LEAF NODE; do
	echo "Fuzz block map for ${attrtype}"
	_scratch_mount
	inum=$(stat -c '%i' $SCRATCH_MNT/ATTR.FMT_${attrtype})
	_scratch_unmount

	_scratch_xfs_fuzz_metadata 'a*.bmx' 'offline'  "inode ${inum}" >> $seqres.full
	echo "Done fuzzing attr map ${attrtype}"
done

# success, all done
status=0
exit
