#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2016, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No. 247
#
# Mount a reflink/rmap filesystem ro (so the per-AG reservation isn't
# created) and unmount, to ensure that we free correctly.
#
. ./common/test_names
_set_seq_and_groups auto quick clone

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/reflink

# real QA test starts here
_supported_fs xfs
_require_scratch_reflink

rm -f $seqres.full

echo "Format and mount"
_scratch_mkfs > $seqres.full 2>&1
_scratch_mount -o ro >> $seqres.full 2>&1

# success, all done
status=0
exit
