#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2012 Red Hat, Inc.  All Rights Reserved.
#
# FS QA Test No. 292
#
# Ensure mkfs with stripe geometry goes into multidisk mode
# which results in more AGs
#
. ./common/test_names
_set_seq_and_groups auto mkfs quick

trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here

# Modify as appropriate.
_supported_fs xfs
_require_test

fsfile=$TEST_DIR/fsfile.$seq

rm -f $fsfile
$XFS_IO_PROG -f -c "truncate 256g" $fsfile

echo "mkfs.xfs without geometry"
mkfs.xfs -f $fsfile | _filter_mkfs 2> $tmp.mkfs > /dev/null
grep -E 'ddev|agcount|agsize' $tmp.mkfs | \
    sed -e "s:$fsfile:FILENAME:g"

echo "mkfs.xfs with cmdline geometry"
mkfs.xfs -f -d su=16k,sw=5 $fsfile | _filter_mkfs 2> $tmp.mkfs > /dev/null
grep -E 'ddev|agcount|agsize' $tmp.mkfs | \
    sed -e "s:$fsfile:FILENAME:g"

rm -f $fsfile

# success, all done
status=0
exit
