#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 349
#
# Populate a XFS filesystem and ensure that scrub and repair are happy.
# Use xfs_repair to fix the corruption.
#
. ./common/test_names
_set_seq_and_groups dangerous_fuzzers scrub

trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_fs xfs

_require_scratch
_require_scrub
_require_populate_commands

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Scrub"
_scratch_mount >> $seqres.full 2>&1
_scratch_scrub >> $seqres.full

# success, all done
status=0
exit
