#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 409
#
# Populate a XFS filesystem and fuzz every rtrmapbt keyptr field.
# Use xfs_scrub to fix the corruption.
#
. ./common/test_names
_set_seq_and_groups dangerous_fuzzers dangerous_scrub dangerous_online_repair realtime

trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_fs xfs
_require_realtime
_require_xfs_scratch_rmapbt
_require_scratch_xfs_fuzz_fields

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Fuzz rtrmapbt keyptrs"
_scratch_xfs_fuzz_metadata '(rtrmapbt)' 'online' 'path -m /realtime/0.rmap' >> $seqres.full
echo "Done fuzzing rtrmapbt keyptrs"

# success, all done
status=0
exit
