#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2018 Oracle, Inc.  All rights reserved.
#
# FS QA Test No. 458
#
# Populate a XFS filesystem and fuzz every bnobt key/pointer.
# Do not fix the filesystem, to test metadata verifiers.

. ./common/test_names
_set_seq_and_groups dangerous_fuzzers dangerous_norepair

trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_fs xfs
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Fuzz bnobt keyptr"
_scratch_xfs_fuzz_metadata '' 'none'  'agf 0' 'addr bnoroot' >> $seqres.full
echo "Done fuzzing bnobt keyptr"

# success, all done
status=0
exit
