#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2018 Oracle, Inc.  All rights reserved.
#
# FS QA Test No. 479
#
# Populate a XFS filesystem and fuzz every node-format attr block field.
# Do not fix the filesystem, to test metadata verifiers.

. ./common/test_names
_set_seq_and_groups dangerous_fuzzers dangerous_norepair

trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_fs xfs
_require_scratch_xfs_fuzz_fields
_disable_dmesg_check

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Find node-format attr block"
_scratch_mount
inum=$(stat -c '%i' $SCRATCH_MNT/ATTR.FMT_NODE)
_scratch_unmount

echo "Fuzz node-format attr block"
_scratch_xfs_fuzz_metadata '' 'none'  "inode ${inum}" "ablock 0" >> $seqres.full
echo "Done fuzzing node-format attr block"

# success, all done
status=0
exit
