#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2021 Oracle.  All Rights Reserved.
#
# FS QA Test No. 713
#
# Populate a XFS filesystem and fuzz every fscounter field.
# Use xfs_scrub to fix the corruption.
#
. ./common/test_names
_set_seq_and_groups dangerous_fuzzers dangerous_scrub dangerous_online_repair

trap "_cleanup; exit \$status" 0 1 2 3 7 15

_cleanup()
{
	cd /
	rm -rf $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/populate
. ./common/fuzzy

# real QA test starts here
_supported_fs xfs
_require_scratch_xfs_fuzz_fields

echo "Format and populate"
_scratch_populate_cached nofill > $seqres.full 2>&1

echo "Fuzz fscounters"
test -z "$SCRATCH_XFS_LIST_METADATA_FIELDS" &&
	SCRATCH_XFS_LIST_METADATA_FIELDS='icount,ifree,fdblocks'
export SCRATCH_XFS_LIST_METADATA_FIELDS
_scratch_xfs_fuzz_metadata '' 'online' 'sb 0' >> $seqres.full
echo "Done fuzzing fscounters"

# success, all done
status=0
exit
