#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2018 Oracle.  All Rights Reserved.
#
# FS QA Test 718
#
# Test formatting with a well known config file.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap '_cleanup; exit $status' 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.* $def_cfgfile $fsimg
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

# Modify as appropriate.
_supported_fs generic
_supported_os Linux
_require_test
_require_scratch_nocheck
_require_xfs_mkfs_cfgfile

def_cfgfile=$TEST_DIR/a
fsimg=$TEST_DIR/a.img
rm -rf $def_cfgfile $fsimg
truncate -s 20t $fsimg

cat > $def_cfgfile << ENDL
[metadata]
crc = 1
rmapbt = 1
reflink = 1

[inode]
sparse = 1
ENDL

$MKFS_XFS_PROG -c $def_cfgfile -f $SCRATCH_DEV > $tmp.mkfs
cat $tmp.mkfs >> $seqres.full
grep -q 'crc=1' $tmp.mkfs || _fail 'v5 not enabled'
grep -q 'rmapbt=1' $tmp.mkfs || _fail 'rmap not enabled'
grep -q 'reflink=1' $tmp.mkfs || _fail 'reflink not enabled'
grep -q 'sparse=1' $tmp.mkfs || _fail 'sparse inodes not enabled'

# success, all done
status=0
exit
