#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2018 Oracle.  All Rights Reserved.
#
# FS QA Test 720
#
# Test formatting with all the distro-provided config files.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap '_cleanup; exit $status' 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.* $def_cfgfile
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

# Modify as appropriate.
_supported_fs generic
_supported_os Linux
_require_test
_require_scratch_nocheck
_require_xfs_mkfs_cfgfile

ls /etc/xfs/mkfs/* 2> /dev/null | while read cfgfile; do
	echo "Format with $cfgfile" >> $seqres.full
	$MKFS_XFS_PROG -c $cfgfile -f $SCRATCH_DEV >> $seqres.full

	short_cfg=$(basename $cfgfile)
	echo "Format with $short_cfg" >> $seqres.full
	$MKFS_XFS_PROG -c $short_cfg -f $SCRATCH_DEV >> $seqres.full
done

# success, all done
status=0
exit
