#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2020, Oracle.  All Rights Reserved.
#
# FS QA Test No. 761
#
# Make sure mkfs sets up enough of the rt geometry that we can compute the
# correct min log size for formatting the fs.

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here
_supported_fs xfs
_require_scratch
_require_realtime

rm -f $seqres.full

# Format a tiny filesystem to force minimum log size, then see if it mounts
_scratch_mkfs -r size=1m -d size=100m > $seqres.full
_scratch_mount >> $seqres.full

# success, all done
status=0
exit
