#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2021 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 819
#
# Race fsstress and rt refcount btree scrub for a while to see if we crash or
# livelock.
#
. ./common/preamble
_begin_fstest online_repair dangerous_fsstress_repair

_cleanup() {
	_scratch_xfs_stress_scrub_cleanup &> /dev/null
	cd /
	rm -r -f $tmp.*
}
_register_cleanup "_cleanup" BUS

# Import common functions.
. ./common/filter
. ./common/fuzzy
. ./common/inject
. ./common/xfs

# real QA test starts here
_supported_fs xfs
_require_realtime
_require_scratch
_require_xfs_stress_online_repair

_scratch_mkfs > "$seqres.full" 2>&1
_scratch_mount
_require_xfs_has_feature "$SCRATCH_MNT" realtime
_require_xfs_has_feature "$SCRATCH_MNT" reflink
_xfs_force_bdev realtime $SCRATCH_MNT

_scratch_xfs_stress_online_repair -s "repair rtrefcountbt"

# success, all done
echo Silence is golden
status=0
exit
