#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2020, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No. 910
#
# Check that we can upgrade a filesystem to support inobtcount and that
# everything works properly after the upgrade.

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# We have very specific formatting parameters, so don't let things get complex
# with realtime devices and external logs.
unset USE_EXTERNAL

# real QA test starts here
_supported_fs xfs
_require_command "$XFS_ADMIN_PROG" "xfs_admin"
_require_xfs_upgrade_inobtcount
_require_xfs_scratch_inobtcount

rm -f $seqres.full

# Make sure we can't format a filesystem with inobtcount and not finobt.
_scratch_mkfs -m crc=1,inobtcount=1,finobt=0 &> $seqres.full && \
	echo "Should not be able to format with inobtcount but not finobt."

# Make sure we can't upgrade a filesystem to inobtcount without finobt.
_scratch_mkfs -m crc=1,inobtcount=0,finobt=0 &> $seqres.full
_scratch_xfs_admin -O inobtcount >> $seqres.full && \
	echo "Should not be able to upgrade to inobtcount without finobt."

# Format V5 filesystem without inode btree counter support and populate it
_scratch_mkfs -m crc=1,inobtcount=0 >> $seqres.full
_scratch_xfs_db -c 'version' -c 'sb 0' -c 'p' >> $seqres.full
_scratch_mount >> $seqres.full

echo moo > $SCRATCH_MNT/urk

_scratch_unmount
_check_scratch_fs

# Now upgrade to inobtcount support
_scratch_xfs_admin -O inobtcount >> $seqres.full
_check_scratch_fs
_scratch_xfs_db -c 'version' -c 'sb 0' -c 'p' -c 'agi 0' -c 'p' >> $seqres.full

# Make sure we have nonzero counters
_scratch_xfs_db -c 'agi 0' -c 'print ino_blocks fino_blocks' | \
	sed -e 's/= [1-9]*/= NONZERO/g'

# Mount again, look at our files
_scratch_mount >> $seqres.full
cat $SCRATCH_MNT/urk

status=0
exit
