#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2024-2025 Oracle.  All Rights Reserved.
#
# FS QA Test 008
#
# Test mount failure capture.
#
. ./common/preamble
_begin_fstest selftest

_require_command "$WIPEFS_PROG" wipefs
_require_scratch

$WIPEFS_PROG -a $SCRATCH_DEV
_scratch_mount &>> $seqres.full

# success, all done
status=0
exit
